source "https://rubygems.org"

ruby "~> 3.3"

gem "rails", "~> 7.2"
gem "mysql2", "~> 0.5"
gem "puma", "~> 6.4"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.8"
gem "sidekiq", "~> 7.2"
gem "redis", "~> 5.1"
gem "elasticsearch", "~> 8.13"
gem "karafka", "~> 2.3"
gem "rack-cors", "~> 2.0"
gem "jbuilder", "~> 2.11"
gem "kaminari", "~> 1.2"
gem "active_model_serializers", "~> 0.10"
gem "pundit", "~> 2.3"
gem "friendly_id", "~> 5.5"
gem "paper_trail", "~> 15.1"
gem "doorkeeper", "~> 5.6"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
  gem "rubocop-rails", "~> 2.23"
  gem "brakeman", "~> 6.1"
end

group :production do
  gem "prometheus_exporter", "~> 2.1"
end
