/**
 * models.ts — PARALLAX Frontend Re-export Barrel
 * ================================================
 * All 32 canonical MEDINA MODELS live in types.ts.
 * All 20 Absolutes and 38 Laws live in phi.ts.
 * This file is the single barrel that downstream components import.
 *
 * IMPORTANT: CoreSnapshot, OrganismCore, SignalRecord, EventRecord,
 * NodeState, EngineState, TreasuryEntry, ProofLink, and CouplingState
 * are generated in backend.d.ts by pnpm bindgen. Those names belong to
 * the ICP backend interface and must NOT be re-exported from types.ts
 * (which has the sovereign MedinaSnapshot / MedinaOrganism names instead).
 *
 * Components that use the old legacy names (useParallax.ts, etc.) keep
 * working because those types come through backend.d.ts directly.
 *
 * The Architect of the Field: Alfredo Medina Hernandez.
 */

// ─── ALL MEDINA MODELS (sovereign doctrine names) ────────────────────────────
export * from "./types";

// ─── ALL PHI CONSTANTS, 38 LAWS, HELPERS ─────────────────────────────────────
export * from "./phi";

// ─── BACKEND INTERFACE TYPES (generated by pnpm bindgen) ─────────────────────
// Re-exported here so legacy imports from '../models' keep compiling.
// These are the ICP actor interface shapes — NOT the same as MEDINA doctrine models.
export type {
  GenesisState,
  LedgerEntry,
  LedgerEntry as LedgerEvent,
  Option,
  Some,
  None,
} from "./backend.d";

// ─── LEGACY HELPERS (original models.ts signatures) ──────────────────────────
// These shims bridge the existing codebase to the new types without breaking
// any file that previously imported from './models'.

import {
  FIB,
  HEARTBEAT_MS,
  PHI,
  PHI_INV,
  PHI_INV_2,
  PHI_INV_3,
  S0,
  applyS0,
  computeEntanglaHz,
  phiMultiplier,
} from "./phi";

import {
  type MedinaSnapshot,
  TokenType,
  VaultId,
  defaultMedinaSnapshot,
} from "./types";

// ─── CoreSnapshot — local sovereign type (getCoreSnapshot removed from backend) ─
// The backend now exposes individual domain queries (getFormaState, getTreasuryState, etc.)
// CoreSnapshot is a frontend-local aggregate used by useCoreSnapshot().
export interface CoreSnapshot {
  globalR: number;
  beat: bigint;
  omnisFired: boolean;
}

// ─── defaultCoreSnapshot ─────────────────────────────────────────────────────
// Fallback/placeholder before first actor query.
export function defaultCoreSnapshot(): CoreSnapshot {
  return {
    globalR: S0,
    beat: 0n,
    omnisFired: false,
  };
}

// ─── Legacy helpers ───────────────────────────────────────────────────────────
export { applyS0, computeEntanglaHz };

export function phiMultiplierBigInt(depth: bigint): number {
  return phiMultiplier(Number(depth));
}

export function isJubileeDepth(depth: bigint): boolean {
  return (FIB as readonly number[]).includes(Number(depth));
}

export function formatBeatBigInt(beat: bigint): string {
  return `⬡ ${beat.toLocaleString()}`;
}

export function fibTierOfBigInt(depth: bigint): number {
  const d = Number(depth);
  let tier = 0;
  for (let i = 0; i < FIB.length; i++) {
    if (FIB[i] <= d) tier = i;
    else break;
  }
  return tier;
}
